"""add tables

Revision ID: 881ca1f7f02b
Revises: 9e33df4e4965
Create Date: 2025-11-22 20:09:35.109331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881ca1f7f02b'
down_revision: Union[str, Sequence[str], None] = '9e33df4e4965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ON_APPROVAL', 'APPROVED', 'EDITED', 'REJECTED', name='emailstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_id'), 'emails', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_id'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
